version: '3'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./config-mosquitto.conf:/mosquitto/config/mosquitto.conf   
  frankenstein:
    image: rocworks/automation-gateway:1.37.1
    ports:
      - "4840:4840"
    environment:
      JAVA_OPTS: '-Xmx1024m'
    volumes:
      - ./config-frankenstein.yaml:/app/config.yaml
      - frankenstein:/app/security

volumes:
    frankenstein:
        external: false